import HeroSection from "@/components/HeroSection";
import Head from "next/head";

export default function Home() {
  // const texts : any = [
  //   {
  //     title: "BYe World",
  //     content: "This is a not a simple Next.js app",
  //   },
  //   {
  //     title: "Only Next.js",
  //     content: "Next.js is a most pupular React framework",
  //   }
  // ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
    </>
  );
}
